-- Insert expert insights from top trading and investment firms
INSERT INTO public.expert_insights (expert_name, expert_title, commodity_focus, title, content, prediction_timeframe, bullish_bearish, confidence_level, published_at) VALUES
('Jeffrey Currie', 'Global Head of Commodities Research - Goldman Sachs', 'energy', 'Oil Market Dynamics Point to $75-80 Range', 'Our analysis suggests crude oil prices will stabilize in the $75-80 range over the next quarter. Supply discipline from OPEC+ combined with steady demand growth from Asia supports this outlook. However, we caution against geopolitical risks that could push prices higher. The recent inventory builds indicate market balance is improving, but seasonal demand patterns will be key.', 'quarterly', 'bullish', 4, '2025-01-05 10:30:00'),

('Natasha Kaneva', 'Head of Global Commodities Strategy - JPMorgan', 'metals', 'Gold Rally to Continue Amid Central Bank Policies', 'We maintain our bullish stance on gold with a 12-month target of $2,150/oz. Central bank dovishness and ongoing geopolitical tensions provide strong tailwinds. The yellow metal continues to serve as a hedge against currency debasement and inflation expectations. Technical indicators support further upside momentum.', 'quarterly', 'bullish', 5, '2025-01-04 14:15:00'),

('Martijn Rats', 'Chief Commodities Strategist - Morgan Stanley', 'energy', 'Natural Gas: Winter Demand vs Storage Levels', 'European natural gas markets remain tight despite adequate storage levels. Weather patterns and industrial demand will be critical factors. We expect price volatility to persist through Q1 2025, with upside risk to our $3.50 forecast if temperatures turn colder than expected.', 'monthly', 'neutral', 3, '2025-01-03 09:45:00'),

('Michael Widmer', 'Head of Metals Research - Bank of America', 'metals', 'Copper Supply Constraints Support Higher Prices', 'Structural supply deficits in copper are becoming increasingly apparent. Mine disruptions in South America and limited new project pipeline support our $4.75/lb target. Green energy transition demand remains robust despite some near-term economic headwinds.', 'quarterly', 'bullish', 4, '2025-01-02 16:20:00'),

('Carlos Casas', 'Senior Analyst - Citi', 'grains', 'Corn Prices Under Pressure from South American Harvest', 'Brazilian and Argentine corn harvests are exceeding expectations, putting downward pressure on global prices. We expect corn futures to test $4.00/bushel support levels. Weather conditions in South America remain favorable, suggesting continued pressure on US exports.', 'monthly', 'bearish', 4, '2025-01-01 11:30:00'),

('Dan Basse', 'President - AgResource Company', 'grains', 'Soybean Complex: China Demand Remains Key Driver', 'Chinese soy import patterns continue to drive global pricing dynamics. Recent trade developments and African Swine Fever recovery support steady demand. We see soybeans finding support at current levels with potential for modest gains if South American weather turns adverse.', 'monthly', 'neutral', 3, '2024-12-30 13:45:00'),

('Ed Morse', 'Global Head of Commodities Research - Citigroup', 'energy', 'Brent-WTI Spread Dynamics Favor Atlantic Basin', 'Transportation costs and regional supply dynamics continue to support Brent premiums over WTI. We expect the spread to maintain $3-5 range through Q1. European refinery margins and Middle East production patterns are key variables to monitor.', 'monthly', 'neutral', 3, '2024-12-29 08:15:00'),

('Vivienne Lloyd', 'Head of Macro and Energy Research - Commonwealth Bank', 'softs', 'Coffee Market Tightness Supports Premium Pricing', 'Brazilian arabica production concerns and Vietnamese robusta export delays are tightening global coffee supplies. We maintain our bullish outlook with arabica futures likely to test $2.00/lb resistance. Climate patterns in key growing regions remain the primary risk factor.', 'quarterly', 'bullish', 4, '2024-12-28 15:30:00'),

('Francisco Blanch', 'Head of Global Commodities Research - Bank of America', 'energy', 'Energy Transition Impact on Oil Demand Peak', 'Our models suggest oil demand may peak earlier than consensus estimates, potentially by 2030. However, near-term fundamentals remain supportive with OPEC spare capacity limited and investment in new supply constrained. This creates a complex investment landscape requiring careful navigation.', 'quarterly', 'neutral', 3, '2024-12-27 12:00:00'),

('Warren Russell', 'Head of Commodities - Macquarie Group', 'livestock', 'Cattle Futures Supported by Tight Supply Dynamics', 'US cattle inventory remains at multi-decade lows while demand patterns show resilience. We expect live cattle futures to find support above $1.85/lb. Drought impacts on pasture conditions and feed costs remain key variables affecting the supply outlook.', 'monthly', 'bullish', 3, '2024-12-26 10:45:00');