-- Insert glossary terms for commodity trading
INSERT INTO glossary_terms (term, definition, category, examples) VALUES
('Futures Contract', 'A standardized legal agreement to buy or sell a commodity at a predetermined price at a specified time in the future.', 'Futures Basics', 'Crude oil futures, gold futures, wheat futures traded on exchanges like NYMEX and CBOT.'),
('Margin', 'The deposit required to open and maintain a futures position, typically 5-15% of the contract value.', 'Futures Basics', 'If crude oil futures are worth $70,000, the margin requirement might be $3,500.'),
('Leverage', 'The ability to control a large position with a relatively small amount of capital through margin trading.', 'Risk Management', 'With $5,000 margin, you might control a $100,000 gold futures contract, providing 20:1 leverage.'),
('Contango', 'A market condition where futures prices are higher than the current spot price, typically indicating oversupply.', 'Market Analysis', 'When December crude oil trades at $72 while current spot price is $70.'),
('Backwardation', 'A market condition where futures prices are lower than the current spot price, typically indicating supply shortage.', 'Market Analysis', 'When December crude oil trades at $68 while current spot price is $70.'),
('Open Interest', 'The total number of outstanding futures contracts that have not been settled or closed.', 'Market Analysis', 'If 50,000 crude oil contracts are open, the open interest is 50,000 contracts.'),
('Tick Size', 'The minimum price movement for a futures contract.', 'Trading Rules', 'Crude oil futures move in $0.01 increments, with each tick worth $10 per contract.'),
('Stop Loss', 'An order to close a position when the price moves against you by a predetermined amount.', 'Risk Management', 'Setting a stop loss at $68 when long crude oil at $70 to limit losses to $2 per barrel.'),
('Spread Trading', 'Simultaneously buying and selling related futures contracts to profit from price differences.', 'Trading Strategies', 'Buying December wheat and selling March wheat to profit from seasonal price differences.'),
('Commercial Trader', 'Market participants who use futures contracts to hedge their business operations involving physical commodities.', 'Market Participants', 'Oil companies, grain elevators, mining companies that hedge their production or consumption.'),
('Speculator', 'Traders who buy and sell futures contracts to profit from price movements without intending to take delivery.', 'Market Participants', 'Fund managers, individual traders, and hedge funds trading for profit rather than hedging.'),
('Basis', 'The difference between the futures price and the cash (spot) price of a commodity.', 'Pricing', 'If wheat futures trade at $6.50 per bushel and local cash price is $6.20, the basis is -30 cents.'),
('Roll Over', 'Closing a position in a near-term futures contract and opening a similar position in a longer-term contract.', 'Trading Operations', 'Closing a March crude oil position and opening an identical June crude oil position.');